channels:
  - conda-forge
  - bioconda
dependencies:
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - eigen=3.4.0
  - expat=2.6.2
  - fftw=3.3.10
  - h5py=3.11.0
  - hdf5=1.14.3
  - icu=75.1
  - krb5=1.21.3
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libitk=5.3.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - mrcfile=1.5.1
  - ncurses=6.5
  - numpy=2.0.0
  - openssl=3.3.1
  - pip=24.0
  - python=3.12.4
  - python_abi=3.12
  - readline=8.2
  - setuptools=70.3.0
  - simpleitk=2.3.1
  - tbb=2021.12.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - anyio==4.4.0
      - backoff==2.2.1
      - boto3==1.34.144
      - botocore==1.34.144
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - cryoet-data-portal==3.0.3
      - deepmerge==1.1.1
      - gql==3.5.0
      - graphql-core==3.2.3
      - idna==3.7
      - jmespath==1.0.1
      - multidict==6.0.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - s3transfer==0.10.2
      - six==1.16.0
      - sniffio==1.3.1
      - tqdm==4.66.4
      - urllib3==2.2.2
      - yarl==1.9.4